apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-test-svc-1-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:ts-idp-poc2/test-svc-1-app.git
        revision: main
        directories:
            - path: yaml
        interval: 1m
  template:
    metadata:
      name: 'test-svc-1-app'
    spec:
      project: test-svc-1
      source:
        repoURL: git@github.com:ts-idp-poc2/test-svc-1-app.git
        targetRevision: main
        path: yaml
        directory:
            recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: "test-svc-1"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true