apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: test-svc-4
    namespace: argocd
spec:
    description: test-svc-4 app project
    destinations:
    - server: https://kubernetes.default.svc
      namespace: "test-svc-4"
    sourceRepos:
    - git@github.com:ts-idp-poc2/test-svc-4-app.git
    - git@github.com:ts-idp-poc2/test-svc-4-infra.git
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceNamespaces:
    - test-svc-4