---
# Role with necessary permissions for running workflows in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets", "serviceaccounts", "events"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "cronworkflows", "workflowtaskresults"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]