---
# RoleBinding to bind the ServiceAccount to the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-runner
  namespace: test-svc-20
subjects:
  - kind: ServiceAccount
    name: run-workflow
    namespace: test-svc-20
roleRef:
  kind: ClusterRole
  name: workflow-runner
  apiGroup: rbac.authorization.k8s.io